[package]
name = "tree-sitter-lalrpop"
version = "0.1.0"
edition = "2024"
description = "LALRPOP grammar for tree-sitter"
readme = "README.md"
repository = "https://github.com/k2d222/tree-sitter-lalrpop"
license = "MIT"
keywords = ["incremental", "lalrpop", "parsing", "tree-sitter"]
categories = ["parser-implementations", "parsing", "text-editors"]
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "/LICENSE",
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json"
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[dev-dependencies]
tree-sitter = "0.27.0"

[build-dependencies]
cc = "1.2"
