[project]
name = "tree-sitter-lalrpop"
version = "0.1.0"
description = "LALRPOP grammar for tree-sitter"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Mathis Brossier", email = "mathis.brossier@gmail.com" }]
keywords = ["incremental", "lalrpop", "parsing", "tree-sitter"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/k2d222/tree-sitter-lalrpop"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
